POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "asdfg",
    "number": "12340987"
}

###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "number": "1234"
}